### ISSUE TITLE
[Suggestion] More secure way to store citizen's GPG keys

### ISSUE THREAD

**Issue by stellessia** [diia-open-source/.github#3]
Hi, I would've to suggest an improvement related to GPG keys.

As a programmer, I'm using GPG keys to sign and verify everything in my sight, but it's very hard to find a good password manager with support of them. If Ukrainian ID passports are using physical fingerprints, why GPG is still not supported by government? It would be a better approach to have an opportunity to generate and store virtual fingerprints that you never lose and don't have to worry that something would ever happen with them. I wanna make it possible to store citizen's GPG keys on secure servers and use, download/export private and public keys easily. To generate just enter your real name or a nickname, add an email and voila! they're stored securely on government servers and connected to other documents, if the keys will ever get stolen it's possible to easily regenerate them.

I hope you'll hear my suggestion and implement it in the future.

Thanks for creating this amazing app!

**Comment by ghost** [comment]
Hi @incycledream 
Thank you for the offer. We will keep this in mind.
